spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/testcontainers"
    username: "root"
    password: "admin"
    driver-class-name: "org.mariadb.jdbc.Driver"
    database-platform: "org.hibernate.dialect.MariaDBDialect"
  jpa:
    hibernate:
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
  liquibase:
    change-log: classpath:db/changelog/db-changelog-main.yml